<?php

/**
 * Implementation of hook_help().
 *
 * @param $path string Path being accessed
 * @param $arg array
 * @return string A localized string containing the help text.
 */
function webfm_ipfolder_help($path, $arg) {
  switch ($path) {
    case 'admin/help#webfm_ipfolder':
      return '<p>'. t('This module extends the Web File Manager. It allows to block or allow certain IP Ranges access to specified folders. <br /> In the !configuration you can provide IP Ranges and folder names.<br /> Depending on your !settings the selected IP Range will be allowed or blocked. By default it <b>blocks</b> access to all folders.', array('!configuration' => l(t('configuration'), 'admin/settings/webfm/permissions/ipfolder'), '!settings' => l(t('settings'), 'admin/settings/webfm/webfm/ipfolder_settings'))) .'</p>';
    case 'admin/modules#description':
      return t('Enable the Web File Manager Extension to allow IP based folder blocking.');
  }
}

/**
 * Implementation hook_file_download().
 *
 * @param String of the file's path.
 *
 * @return NULL|-1|array dont care about this file|access denied|headers
 */
function webfm_ipfolder_file_download($filepath) {
  if (!_webfm_managed_by_webfm($filepath) OR user_access('administer webfm')) {
    //file is not within webfm tree
    //OR user is an admin we don't need to do anything.
    return NULL;
  }

  $match = FALSE; //default:nothing found
 
  $file_folders = trim(str_replace(file_directory_path(), '', $filepath), '/\\'); //strip drupal root directory, and leading or tailing slashes
  $file_folders = explode('/', $file_folders); //expand to single directories
  array_pop($file_folders); //pop off file name
  $file_folders = array_flip($file_folders); //flip array for easier search with array_key_exists

  //get folders for this ip
  //this is based upon ipauth_get_ip_authenticators from ipauth.module
  $sql = "SELECT folder FROM {webfm_ipfolder} WHERE ((ip1 = '%s') OR (ip1 <> 0 AND ip1 <= '%s' AND ip2 >= '%s'))"; //get folders within ip range or for single ip match
  $ip = sprintf("%u", ip2long(ip_address())); //users current ip

  if ($result = db_query($sql, $ip, $ip, $ip)) {
    //we have to matches for this range
    while ($db_folders = db_fetch_object($result)) {
      //compare all folders found w/ folders of current file
      $match = array_key_exists($db_folders->folder, $file_folders);//set match to true if folders in range
    }
  }

  //check access, default is to deny all access, but to specified folders
  if ($match == variable_get('webfm_ipfolder_bydefault', FALSE)) {
    return -1;
  }

  return NULL;
}

/**
 * Implementation of hook_menu().
 * @see webfm_ipfolder.admin.inc
 *
 * @return array
 */
function webfm_ipfolder_menu() {
  $items = array();
  $items['admin/settings/webfm/permissions/ipfolder'] = array(
  'title' => 'IP based folder access',
  'description' => 'Configure IP based folder access.',
  'file' => 'webfm_ipfolder.admin.inc',
  'page callback' => 'drupal_get_form',
  'page arguments' => array('webfm_ipfolder_ips'),
  'access arguments' => array('administer webfm'),
  'type' =>  MENU_LOCAL_TASK,
  );
  $items['admin/settings/webfm/permissions/ipfolder/edit'] = array(
  'title' => t('WebFM IP based folder access -- Modify'),
  'page callback' => 'drupal_get_form',
  'page arguments' => array('webfm_ipfolder_ips_edit'),
  'access callback' => 'user_access',    
  'access arguments' => Array('administer webfm'),
  'file' => 'webfm_ipfolder.admin.inc',
  'type' => MENU_CALLBACK,
  );
  $items['admin/settings/webfm/permissions/ipfolder/delete'] = array(
  'title' => t('WebFM IP based folder access -- Delete'),
  'page callback' => 'drupal_get_form',
  'page arguments' => array('webfm_ipfolder_ips_delete'),
  'access callback' => 'user_access',    
  'access arguments' => Array('administer webfm'),
  'file' => 'webfm_ipfolder.admin.inc',
  'type' => MENU_CALLBACK,
  );
  $items['admin/settings/webfm/webfm/ipfolder_settings'] = array(
  'title' => 'IP based folder access',
  'description' => 'Configure IP based folder access - default behavior',
  'file' => 'webfm_ipfolder.admin.inc',
  'page callback' => 'drupal_get_form',
  'page arguments' => array('webfm_ipfolder_settings'),
  'access arguments' => array('administer webfm'),
  'type' =>  MENU_LOCAL_TASK,
  'weight' => 1,
  ); 
  return $items;
}